/* CARINFO 데이터베이스 생성 */
CREATE USER CARINFO
IDENTIFIED BY qwer1234
DEFAULT TABLESPACE USERS;

GRANT CONNECT, RESOURCE TO CARINFO;

/* CARINFO 테이블 생성 스크립트 */
CREATE TABLE ATCH_FILE
(
    FILE_NO    NUMBER(10) NOT NULL,
    TBL_NM    VARCHAR2(50) NOT NULL,
    FILE_IDNT_NO    VARCHAR2(10) NOT NULL,
    FILE_TY_CD    VARCHAR2(6) NOT NULL,
    FILE_SRT_ORD    NUMBER(3) NOT NULL,
    FILE_PATH_NM    VARCHAR2(500) NOT NULL,
    ORG_FILE_NM    VARCHAR2(500) NOT NULL,
    FILE_NM    VARCHAR2(100) NOT NULL,
    FILE_EXT_NM    VARCHAR2(6) NOT NULL,
    MIME_TY    VARCHAR2(100) NOT NULL,
    FILE_SIZE    NUMBER(10) NOT NULL,
    FILE_DOWN_CNT    NUMBER(5) NOT NULL,
    CAPTION    VARCHAR2(200),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN ATCH_FILE.FILE_NO IS '파일번호';

COMMENT ON COLUMN ATCH_FILE.TBL_NM IS '테이블명';

COMMENT ON COLUMN ATCH_FILE.FILE_IDNT_NO IS '파일식별번호';

COMMENT ON COLUMN ATCH_FILE.FILE_TY_CD IS '파일유형코드(100)';

COMMENT ON COLUMN ATCH_FILE.FILE_SRT_ORD IS '파일정렬순서';

COMMENT ON COLUMN ATCH_FILE.FILE_PATH_NM IS '파일경로명';

COMMENT ON COLUMN ATCH_FILE.ORG_FILE_NM IS '원본파일명';

COMMENT ON COLUMN ATCH_FILE.FILE_NM IS '파일명';

COMMENT ON COLUMN ATCH_FILE.FILE_EXT_NM IS '파일확장자명';

COMMENT ON COLUMN ATCH_FILE.MIME_TY IS '마임타입';

COMMENT ON COLUMN ATCH_FILE.FILE_SIZE IS '파일크기';

COMMENT ON COLUMN ATCH_FILE.FILE_DOWN_CNT IS '파일다운횟수';

COMMENT ON COLUMN ATCH_FILE.CAPTION IS '캡션';

COMMENT ON COLUMN ATCH_FILE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN ATCH_FILE.REG_NO IS '등록자';

COMMENT ON COLUMN ATCH_FILE.REG_DTT IS '등록일시';

COMMENT ON COLUMN ATCH_FILE.MOD_NO IS '수정자';

COMMENT ON COLUMN ATCH_FILE.MOD_DTT IS '수정일시';

COMMENT ON TABLE ATCH_FILE IS '첨부파일';

CREATE UNIQUE INDEX ATCH_FILE_PK ON ATCH_FILE
( FILE_NO );

ALTER TABLE ATCH_FILE
 ADD CONSTRAINT ATCH_FILE_PK PRIMARY KEY ( FILE_NO )
 USING INDEX ATCH_FILE_PK;


CREATE TABLE CAR_MDL
(
    CAR_MDL_NO    VARCHAR2(14) NOT NULL,
    CAR_MDL_NM    VARCHAR2(100) NOT NULL,
    MNF_NO    VARCHAR2(6) NOT NULL,
    CAR_APRN_CD    VARCHAR2(6) NOT NULL,
    CAR_KN_CD    VARCHAR2(6) NOT NULL,
    SRT_ORD    NUMBER(3),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN CAR_MDL.CAR_MDL_NO IS '자동차모델번호';

COMMENT ON COLUMN CAR_MDL.CAR_MDL_NM IS '자동차모델명';

COMMENT ON COLUMN CAR_MDL.MNF_NO IS '제조사번호';

COMMENT ON COLUMN CAR_MDL.CAR_APRN_CD IS '자동차외형코드(102)';

COMMENT ON COLUMN CAR_MDL.CAR_KN_CD IS '자동차종류코드(103)';

COMMENT ON COLUMN CAR_MDL.SRT_ORD IS '정렬순서';

COMMENT ON COLUMN CAR_MDL.DEL_YN IS '삭제여부';

COMMENT ON COLUMN CAR_MDL.REG_NO IS '등록자';

COMMENT ON COLUMN CAR_MDL.REG_DTT IS '등록일시';

COMMENT ON COLUMN CAR_MDL.MOD_NO IS '수정자';

COMMENT ON COLUMN CAR_MDL.MOD_DTT IS '수정일시';

COMMENT ON TABLE CAR_MDL IS '자동차모델';

CREATE UNIQUE INDEX CAR_MDL_PK ON CAR_MDL
( CAR_MDL_NO );

ALTER TABLE CAR_MDL
 ADD CONSTRAINT CAR_MDL_PK PRIMARY KEY ( CAR_MDL_NO )
 USING INDEX CAR_MDL_PK;


CREATE TABLE CAR_MDL_FILE
(
    CAR_MDL_NO    VARCHAR2(14) NOT NULL,
    RLS_YEAR    VARCHAR2(4) NOT NULL,
    FILE_SEQ    NUMBER(10) NOT NULL,
    CAR_MDL_FILE_CL_CD    VARCHAR2(6) NOT NULL,
    FILE_TY_CD    VARCHAR2(6) NOT NULL,
    FILE_SRT_ORD    NUMBER(3) NOT NULL,
    FILE_PATH_NM    VARCHAR2(500) NOT NULL,
    ORG_FILE_NM    VARCHAR2(500) NOT NULL,
    FILE_NM    VARCHAR2(100) NOT NULL,
    FILE_EXT_NM    VARCHAR2(6) NOT NULL,
    MIME_TY    VARCHAR2(100) NOT NULL,
    FILE_SIZE    NUMBER(10) NOT NULL,
    FILE_DOWN_CNT    NUMBER(5) NOT NULL,
    CAPTION    VARCHAR2(200),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN CAR_MDL_FILE.CAR_MDL_NO IS '자동차모델번호';

COMMENT ON COLUMN CAR_MDL_FILE.RLS_YEAR IS '출시년도';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_SEQ IS '파일순번';

COMMENT ON COLUMN CAR_MDL_FILE.CAR_MDL_FILE_CL_CD IS '자동차모델파일분류코드(109)';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_TY_CD IS '파일유형코드(100)';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_SRT_ORD IS '파일정렬순서';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_PATH_NM IS '파일경로명';

COMMENT ON COLUMN CAR_MDL_FILE.ORG_FILE_NM IS '원본파일명';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_NM IS '파일명';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_EXT_NM IS '파일확장자명';

COMMENT ON COLUMN CAR_MDL_FILE.MIME_TY IS '마임타입';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_SIZE IS '파일크기';

COMMENT ON COLUMN CAR_MDL_FILE.FILE_DOWN_CNT IS '파일다운횟수';

COMMENT ON COLUMN CAR_MDL_FILE.CAPTION IS '캡션';

COMMENT ON COLUMN CAR_MDL_FILE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN CAR_MDL_FILE.REG_NO IS '등록자';

COMMENT ON COLUMN CAR_MDL_FILE.REG_DTT IS '등록일시';

COMMENT ON COLUMN CAR_MDL_FILE.MOD_NO IS '수정자';

COMMENT ON COLUMN CAR_MDL_FILE.MOD_DTT IS '수정일시';

COMMENT ON TABLE CAR_MDL_FILE IS '자동차모델파일';

CREATE UNIQUE INDEX CAR_MDL_FILE_PK ON CAR_MDL_FILE
( CAR_MDL_NO,RLS_YEAR,FILE_SEQ );

ALTER TABLE CAR_MDL_FILE
 ADD CONSTRAINT CAR_MDL_FILE_PK PRIMARY KEY ( CAR_MDL_NO,RLS_YEAR,FILE_SEQ )
 USING INDEX CAR_MDL_FILE_PK;


CREATE TABLE CAR_MDL_YEAR
(
    CAR_MDL_NO    VARCHAR2(14) NOT NULL,
    RLS_YEAR    VARCHAR2(4) NOT NULL,
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN CAR_MDL_YEAR.CAR_MDL_NO IS '자동차모델번호';

COMMENT ON COLUMN CAR_MDL_YEAR.RLS_YEAR IS '출시년도';

COMMENT ON COLUMN CAR_MDL_YEAR.DEL_YN IS '삭제여부';

COMMENT ON COLUMN CAR_MDL_YEAR.REG_NO IS '등록자';

COMMENT ON COLUMN CAR_MDL_YEAR.REG_DTT IS '등록일시';

COMMENT ON COLUMN CAR_MDL_YEAR.MOD_NO IS '수정자';

COMMENT ON COLUMN CAR_MDL_YEAR.MOD_DTT IS '수정일시';

COMMENT ON TABLE CAR_MDL_YEAR IS '자동차모델연식';

CREATE UNIQUE INDEX CAR_MDL_YEAR_PK ON CAR_MDL_YEAR
( CAR_MDL_NO,RLS_YEAR );

ALTER TABLE CAR_MDL_YEAR
 ADD CONSTRAINT CAR_MDL_YEAR_PK PRIMARY KEY ( CAR_MDL_NO,RLS_YEAR )
 USING INDEX CAR_MDL_YEAR_PK;


CREATE TABLE CAR_RTG_MDL
(
    CAR_RTG_MDL_NO    VARCHAR2(14) NOT NULL,
    CAR_RTG_MDL_NM    VARCHAR2(100) NOT NULL,
    CAR_MDL_NO    VARCHAR2(14) NOT NULL,
    RLS_YEAR    VARCHAR2(4) NOT NULL,
    SRT_ORD    NUMBER(3),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN CAR_RTG_MDL.CAR_RTG_MDL_NO IS '자동차등급모델번호';

COMMENT ON COLUMN CAR_RTG_MDL.CAR_RTG_MDL_NM IS '자동차등급모델명';

COMMENT ON COLUMN CAR_RTG_MDL.CAR_MDL_NO IS '자동차모델번호';

COMMENT ON COLUMN CAR_RTG_MDL.RLS_YEAR IS '출시년도';

COMMENT ON COLUMN CAR_RTG_MDL.SRT_ORD IS '정렬순서';

COMMENT ON COLUMN CAR_RTG_MDL.DEL_YN IS '삭제여부';

COMMENT ON COLUMN CAR_RTG_MDL.REG_NO IS '등록자';

COMMENT ON COLUMN CAR_RTG_MDL.REG_DTT IS '등록일시';

COMMENT ON COLUMN CAR_RTG_MDL.MOD_NO IS '수정자';

COMMENT ON COLUMN CAR_RTG_MDL.MOD_DTT IS '수정일시';

COMMENT ON TABLE CAR_RTG_MDL IS '자동차등급모델';

CREATE UNIQUE INDEX CAR_RTG_MDL_PK ON CAR_RTG_MDL
( CAR_RTG_MDL_NO );

ALTER TABLE CAR_RTG_MDL
 ADD CONSTRAINT CAR_RTG_MDL_PK PRIMARY KEY ( CAR_RTG_MDL_NO )
 USING INDEX CAR_RTG_MDL_PK;


CREATE TABLE CAR_RTG_MDL_DTL
(
    CAR_RTG_MDL_NO    VARCHAR2(14) NOT NULL,
    ENGN_TY_CD    VARCHAR2(6),
    SPRC_MTHD_CD    VARCHAR2(6),
    AMN_EXH    VARCHAR2(4),
    FUEL_KN_CD    VARCHAR2(6) NOT NULL,
    FUEL_EFCN    NUMBER(2),
    PSNG_NUM    NUMBER(2),
    DRV_MTH_CD    VARCHAR2(6),
    GRBX_TY_CD    VARCHAR2(6),
    GRBX_STAG    NUMBER(2),
    MAX_OTPT    NUMBER(3),
    MAX_TRQ    NUMBER(2),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN CAR_RTG_MDL_DTL.CAR_RTG_MDL_NO IS '자동차등급모델번호';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.ENGN_TY_CD IS '엔진유형코드(104)';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.SPRC_MTHD_CD IS '과급방식코드(105)';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.AMN_EXH IS '배기량';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.FUEL_KN_CD IS '연료종류코드(106)';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.FUEL_EFCN IS '연비';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.PSNG_NUM IS '승차인원';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.DRV_MTH_CD IS '구동방식코드(107)';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.GRBX_TY_CD IS '변속기유형코드(108)';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.GRBX_STAG IS '변속기단계';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.MAX_OTPT IS '최대출력';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.MAX_TRQ IS '최대토크';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.DEL_YN IS '삭제여부';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.REG_NO IS '등록자';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.REG_DTT IS '등록일시';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.MOD_NO IS '수정자';

COMMENT ON COLUMN CAR_RTG_MDL_DTL.MOD_DTT IS '수정일시';

COMMENT ON TABLE CAR_RTG_MDL_DTL IS '자동차등급모델상세';

CREATE UNIQUE INDEX CAR_RTG_MDL_DTL_PK ON CAR_RTG_MDL_DTL
( CAR_RTG_MDL_NO );

ALTER TABLE CAR_RTG_MDL_DTL
 ADD CONSTRAINT CAR_RTG_MDL_DTL_PK PRIMARY KEY ( CAR_RTG_MDL_NO )
 USING INDEX CAR_RTG_MDL_DTL_PK;


CREATE TABLE CAR_RTG_TRIM
(
    CAR_RTG_TRIM_NO    VARCHAR2(14) NOT NULL,
    CAR_RTG_MDL_NO    VARCHAR2(14) NOT NULL,
    CAR_RTG_TRIM_NM    VARCHAR2(100) NOT NULL,
    RLS_PRICE    NUMBER(10),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN CAR_RTG_TRIM.CAR_RTG_TRIM_NO IS '자동차등급트림번호';

COMMENT ON COLUMN CAR_RTG_TRIM.CAR_RTG_MDL_NO IS '자동차등급모델번호';

COMMENT ON COLUMN CAR_RTG_TRIM.CAR_RTG_TRIM_NM IS '자동차등급트림명';

COMMENT ON COLUMN CAR_RTG_TRIM.RLS_PRICE IS '출시가';

COMMENT ON COLUMN CAR_RTG_TRIM.DEL_YN IS '삭제여부';

COMMENT ON COLUMN CAR_RTG_TRIM.REG_NO IS '등록자';

COMMENT ON COLUMN CAR_RTG_TRIM.REG_DTT IS '등록일시';

COMMENT ON COLUMN CAR_RTG_TRIM.MOD_NO IS '수정자';

COMMENT ON COLUMN CAR_RTG_TRIM.MOD_DTT IS '수정일시';

COMMENT ON TABLE CAR_RTG_TRIM IS '자동차등급트림';

CREATE UNIQUE INDEX CAR_RTG_TRIM_PK ON CAR_RTG_TRIM
( CAR_RTG_TRIM_NO,CAR_RTG_MDL_NO );

ALTER TABLE CAR_RTG_TRIM
 ADD CONSTRAINT CAR_RTG_TRIM_PK PRIMARY KEY ( CAR_RTG_TRIM_NO,CAR_RTG_MDL_NO )
 USING INDEX CAR_RTG_TRIM_PK;


CREATE TABLE CMN_CODE
(
    CMN_CD    VARCHAR2(6) NOT NULL,
    CMN_CD_NM    VARCHAR2(100) NOT NULL,
    UP_CMN_CD    VARCHAR2(6) NOT NULL,
    USE_YN    VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SRT_ORD    NUMBER(3),
    NOTE    VARCHAR2(200),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN CMN_CODE.CMN_CD IS '공통코드';

COMMENT ON COLUMN CMN_CODE.CMN_CD_NM IS '공통코드명';

COMMENT ON COLUMN CMN_CODE.UP_CMN_CD IS '상위공통코드';

COMMENT ON COLUMN CMN_CODE.USE_YN IS '사용여부';

COMMENT ON COLUMN CMN_CODE.SRT_ORD IS '정렬순서';

COMMENT ON COLUMN CMN_CODE.NOTE IS '비고';

COMMENT ON COLUMN CMN_CODE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN CMN_CODE.REG_NO IS '등록자';

COMMENT ON COLUMN CMN_CODE.REG_DTT IS '등록일시';

COMMENT ON COLUMN CMN_CODE.MOD_NO IS '수정자';

COMMENT ON COLUMN CMN_CODE.MOD_DTT IS '수정일시';

COMMENT ON TABLE CMN_CODE IS '공통코드';

CREATE UNIQUE INDEX CMN_CODE_PK ON CMN_CODE
( CMN_CD );

ALTER TABLE CMN_CODE
 ADD CONSTRAINT CMN_CODE_PK PRIMARY KEY ( CMN_CD )
 USING INDEX CMN_CODE_PK;


CREATE TABLE MNF
(
    MNF_NO    VARCHAR2(6) NOT NULL,
    MNF_NM    VARCHAR2(50) NOT NULL,
    NTN_CD    VARCHAR2(3) NOT NULL,
    SRT_ORD    NUMBER(3),
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN MNF.MNF_NO IS '제조사번호';

COMMENT ON COLUMN MNF.MNF_NM IS '제조사명';

COMMENT ON COLUMN MNF.NTN_CD IS '국가코드';

COMMENT ON COLUMN MNF.SRT_ORD IS '정렬순서';

COMMENT ON COLUMN MNF.DEL_YN IS '삭제여부';

COMMENT ON COLUMN MNF.REG_NO IS '등록자';

COMMENT ON COLUMN MNF.REG_DTT IS '등록일시';

COMMENT ON COLUMN MNF.MOD_NO IS '수정자';

COMMENT ON COLUMN MNF.MOD_DTT IS '수정일시';

COMMENT ON TABLE MNF IS '제조사';

CREATE UNIQUE INDEX MNF_PK ON MNF
( MNF_NO );

ALTER TABLE MNF
 ADD CONSTRAINT MNF_PK PRIMARY KEY ( MNF_NO )
 USING INDEX MNF_PK;


CREATE TABLE NTN_CODE
(
    NTN_CD    VARCHAR2(3) NOT NULL,
    NTN_CD_KR_NM    VARCHAR2(50) NOT NULL,
    NTN_CD_EN_NM    VARCHAR2(25) NOT NULL,
    USE_YN    VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DEL_YN    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REG_NO    NUMBER(10) NOT NULL,
    REG_DTT    DATE NOT NULL,
    MOD_NO    NUMBER(10) NOT NULL,
    MOD_DTT    DATE NOT NULL
);

COMMENT ON COLUMN NTN_CODE.NTN_CD IS '국가코드';

COMMENT ON COLUMN NTN_CODE.NTN_CD_KR_NM IS '국가코드한글명';

COMMENT ON COLUMN NTN_CODE.NTN_CD_EN_NM IS '국가코드영문명';

COMMENT ON COLUMN NTN_CODE.USE_YN IS '사용여부';

COMMENT ON COLUMN NTN_CODE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN NTN_CODE.REG_NO IS '등록자';

COMMENT ON COLUMN NTN_CODE.REG_DTT IS '등록일시';

COMMENT ON COLUMN NTN_CODE.MOD_NO IS '수정자';

COMMENT ON COLUMN NTN_CODE.MOD_DTT IS '수정일시';

COMMENT ON TABLE NTN_CODE IS '국가코드';

CREATE UNIQUE INDEX NTN_CODE_PK ON NTN_CODE
( NTN_CD );

ALTER TABLE NTN_CODE
 ADD CONSTRAINT NTN_CODE_PK PRIMARY KEY ( NTN_CD )
 USING INDEX NTN_CODE_PK;


